apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: producer
spec:
  ports:
  - port: 30001
    protocol: TCP
  clusterIP: None
  selector:
    app: producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: producer
